ITS#10472 Check tool return codes when missing

diff --git a/contrib/slapd-modules/variant/tests/scripts/test001-config b/contrib/slapd-modules/variant/tests/scripts/test001-config
--- a/contrib/slapd-modules/variant/tests/scripts/test001-config
+++ b/contrib/slapd-modules/variant/tests/scripts/test001-config
@@ -96,6 +96,12 @@ echo "database config" >>$CONF2
 echo "rootpw `$SLAPPASSWD -T $CONFIGPWF`" >>$CONF2
 
 $SLAPADD -f $CONF2 -l $LDIFORDERED
+RC=$?
+if test $RC != 0 ; then
+	echo "slapadd failed ($RC)!"
+	exit $RC
+fi
+
 $SLAPD -Tt -f $CONF2 -F $TESTDIR/conftest -d $LVL >> $LOG2 2>&1
 RC=$?
 if test $RC != 0 ; then
diff --git a/tests/data/regressions/its8427/its8427 b/tests/data/regressions/its8427/its8427
--- a/tests/data/regressions/its8427/its8427
+++ b/tests/data/regressions/its8427/its8427
@@ -130,6 +130,11 @@ EOF
 echo "Configuring provider"
 cd $TESTDIR/srv1
 $SLAPADD -F ./slapd.d -n 0 -d-1 < $TMP > $TESTOUT 2>&1
+RC=$?
+if test $RC != 0 ; then
+	echo "slapadd failed ($RC)!"
+	exit $RC
+fi
 
 $SLAPADD -F ./slapd.d -n 0 -d-1 <<EOF >> $TESTOUT 2>&1
 dn: olcOverlay=syncprov,olcDatabase={1}$BACKEND,cn=config
@@ -137,6 +142,12 @@ objectClass: olcOverlayConfig
 objectClass: olcSyncProvConfig
 olcOverlay: syncprov
 EOF
+
+RC=$?
+if test $RC != 0 ; then
+	echo "slapadd failed ($RC)!"
+	exit $RC
+fi
 
 echo "Starting provider..."
 $SLAPD -F ./slapd.d -h "$SURIP1 ldaps://127.0.0.2:$PORT1" -d $LVL > $LOG1 2>&1 &
@@ -169,6 +180,11 @@ fi
 echo "Configuring consumer"
 cd $TESTDIR/srv2
 $SLAPADD -F ./slapd.d -n 0 -d-1 < $TMP >> $TESTOUT 2>&1
+RC=$?
+if test $RC != 0 ; then
+	echo "slapadd failed ($RC)!"
+	exit $RC
+fi
 
 $SLAPMODIFY -F ./slapd.d -n 0 -d-1 <<EOF >> $TESTOUT 2>&1
 dn: olcDatabase={1}$BACKEND,cn=config
@@ -179,6 +195,12 @@ olcSyncRepl: rid=001 provider=ldaps://127.0.0.2:$PORT1
   searchbase="$BASEDN" $SYNCTYPE retry="3 +" timeout=3
   tls_cacert=$TESTDIR/tls/ca/certs/testsuiteCA.crt tls_reqcert=allow
 EOF
+
+RC=$?
+if test $RC != 0 ; then
+	echo "slapmodify failed ($RC)!"
+	exit $RC
+fi
 
 echo "Starting consumer..."
 $SLAPD -F ./slapd.d -h $URI2 -d $LVL > $LOG2 2>&1 &
diff --git a/tests/data/regressions/its8444/its8444 b/tests/data/regressions/its8444/its8444
--- a/tests/data/regressions/its8444/its8444
+++ b/tests/data/regressions/its8444/its8444
@@ -61,6 +61,12 @@ while [ $n -le $MPR ]; do
 	mkdir -p ${XDIR}$n $DBDIR.1 $DBDIR.2 $CFDIR
 	. $CONFFILTER $BACKEND < $ITSDIR/slapd-provider${n}.ldif > $CONFLDIF
 	$SLAPADD -F $CFDIR -n 0 -l $CONFLDIF
+	RC=$?
+	if test $RC != 0 ; then
+		echo "slapadd failed ($RC)!"
+		exit $RC
+	fi
+
 	n=`expr $n + 1`
 done
 
diff --git a/tests/data/regressions/its8521/its8521 b/tests/data/regressions/its8521/its8521
--- a/tests/data/regressions/its8521/its8521
+++ b/tests/data/regressions/its8521/its8521
@@ -47,6 +47,12 @@ ITSDIR=$DATADIR/regressions/its$ITS
 echo "Starting provider slapd on TCP/IP port $PORT1..."
 . $CONFFILTER $BACKEND < $ITSDIR/slapd-provider.ldif > $CONFLDIF
 $SLAPADD -F $CFPRO -n 0 -l $CONFLDIF
+RC=$?
+if test $RC != 0 ; then
+	echo "slapadd failed ($RC)!"
+	exit $RC
+fi
+
 $SLAPD -F $CFPRO -h $URI1 -d $LVL > $LOG1 2>&1 &
 PID=$!
 if test $WAIT != 0 ; then
@@ -78,6 +84,12 @@ fi
 echo "Starting consumer slapd on TCP/IP port $PORT2..."
 . $CONFFILTER $BACKEND < $ITSDIR/slapd-consumer.ldif > $CONFLDIF
 $SLAPADD -F $CFCON -n 0 -l $CONFLDIF
+RC=$?
+if test $RC != 0 ; then
+	echo "slapadd failed ($RC)!"
+	exit $RC
+fi
+
 $SLAPD -F $CFCON -h $URI2 -d $LVL > $LOG2 2>&1 &
 SLAVEPID=$!
 if test $WAIT != 0 ; then
diff --git a/tests/data/regressions/its8663/its8663 b/tests/data/regressions/its8663/its8663
--- a/tests/data/regressions/its8663/its8663
+++ b/tests/data/regressions/its8663/its8663
@@ -40,6 +40,12 @@ ITSDIR=$DATADIR/regressions/its$ITS
 echo "Starting provider slapd on TCP/IP port $PORT1..."
 . $CONFFILTER $BACKEND < $ITSDIR/slapd-provider.ldif > $CONFLDIF
 $SLAPADD -F $CFPRO -n 0 -l $CONFLDIF
+RC=$?
+if test $RC != 0 ; then
+	echo "slapadd failed ($RC)!"
+	exit $RC
+fi
+
 $SLAPD -F $CFPRO -h $URI1 -d $LVL > $LOG1 2>&1 &
 PID=$!
 if test $WAIT != 0 ; then
diff --git a/tests/data/regressions/its8667/its8667 b/tests/data/regressions/its8667/its8667
--- a/tests/data/regressions/its8667/its8667
+++ b/tests/data/regressions/its8667/its8667
@@ -38,6 +38,11 @@ ITSDIR=$DATADIR/regressions/its$ITS
 echo "Starting slapd on TCP/IP port $PORT1..."
 . $CONFFILTER $BACKEND < $ITSDIR/slapd.ldif > $CONFLDIF
 $SLAPADD -F $CFPRO -n 0 -l $CONFLDIF
+RC=$?
+if test $RC != 0 ; then
+	echo "slapadd failed ($RC)!"
+	exit $RC
+fi
 
 echo "Populating root database..."
 $SLAPADD -F $CFPRO -b "dc=example,dc=com" -l $ITSDIR/root.ldif >> $TESTOUT 2>&1
diff --git a/tests/data/regressions/its9051/its9051 b/tests/data/regressions/its9051/its9051
--- a/tests/data/regressions/its9051/its9051
+++ b/tests/data/regressions/its9051/its9051
@@ -38,7 +38,18 @@ echo "Initializing server configuration for provider..."
 mkdir -p ${XDIR} $DBDIR.1 $DBDIR.2 $CFDIR
 . $CONFFILTER $BACKEND < $ITSDIR/slapd-provider.ldif > $CONFLDIF
 $SLAPADD -F $CFDIR -n 0 -l $CONFLDIF
+RC=$?
+if test $RC != 0 ; then
+	echo "slapadd failed ($RC)!"
+	exit $RC
+fi
+
 $SLAPADD -F $CFDIR -q -b $BASEDN -l $ITSDIR/db.ldif
+RC=$?
+if test $RC != 0 ; then
+	echo "slapadd failed ($RC)!"
+	exit $RC
+fi
 
 KILLPIDS=
 CFDIR=${XDIR}/slapd.d
diff --git a/tests/data/regressions/its9282/its9282 b/tests/data/regressions/its9282/its9282
--- a/tests/data/regressions/its9282/its9282
+++ b/tests/data/regressions/its9282/its9282
@@ -56,6 +56,12 @@ while [ $n -le $MMR ]; do
 	fi
 	sed -e "s/@SID@/$n/g" -e "s|@URI@|$MYURI|g" $TESTDIR/config${n}.ldif > $CONFLDIF
 	$SLAPADD -F $CFDIR -n 0 -l $CONFLDIF
+	RC=$?
+	if test $RC != 0 ; then
+		echo "slapadd failed ($RC)!"
+		exit $RC
+	fi
+
 	n=`expr $n + 1`
 done
 
diff --git a/tests/data/regressions/its9863/its9863 b/tests/data/regressions/its9863/its9863
--- a/tests/data/regressions/its9863/its9863
+++ b/tests/data/regressions/its9863/its9863
@@ -62,6 +62,12 @@ cp $ITSDIR/db.ldif $TESTDIR
 echo "Running slapadd to build database on the provider..."
 . $CONFFILTER $BACKEND <  $ITSDIR/slapd-provider.ldif > $CONFLDIF
 $SLAPADD -F $PDIR/slapd.d -n 0 -l $CONFLDIF
+RC=$?
+if test $RC != 0 ; then
+	echo "slapadd failed ($RC)!"
+	exit $RC
+fi
+
 $SLAPADD -F $PDIR/slapd.d -q -b $BASEDN -l $TESTDIR/db.ldif
 RC=$?
 if test $RC != 0 ; then
@@ -104,6 +110,12 @@ fi
 echo "Starting slapd consumer on TCP/IP port $PORT3 and ${PORT4}..."
 . $CONFFILTER $BACKEND < $ITSDIR/slapd-consumer.ldif > $CONF2
 $SLAPADD -F $CDIR/slapd.d -n 0 -l $CONF2
+RC=$?
+if test $RC != 0 ; then
+	echo "slapadd failed ($RC)!"
+	exit $RC
+fi
+
 $SLAPD -F $CDIR/slapd.d -h "$URI3 $SURI4" -d $LVL > $LOG2 2>&1 &
 CONSPID=$!
 if test $WAIT != 0 ; then
diff --git a/tests/data/regressions/its9888/its9888 b/tests/data/regressions/its9888/its9888
--- a/tests/data/regressions/its9888/its9888
+++ b/tests/data/regressions/its9888/its9888
@@ -59,6 +59,12 @@ esac
 echo "Starting provider slapd on TCP/IP port $PORT1..."
 . $CONFFILTER $BACKEND < $DYNAMICCONF > $CONFLDIF
 $SLAPADD -F $CFPRO -n 0 -l $CONFLDIF
+RC=$?
+if test $RC != 0 ; then
+	echo "slapadd failed ($RC)!"
+	exit $RC
+fi
+
 $SLAPD -F $CFPRO -h $URI1 -d $LVL > $LOG1 2>&1 &
 PROVIDERPID=$!
 if test $WAIT != 0 ; then
@@ -184,6 +190,12 @@ fi
 
 echo "Starting consumer slapd on TCP/IP port $PORT2..."
 $SLAPADD -F $CFCON -n 0 -l $CONFLDIF
+RC=$?
+if test $RC != 0 ; then
+	echo "slapadd failed ($RC)!"
+	exit $RC
+fi
+
 $SLAPD -F $CFCON -h $URI2 -d $LVL > $LOG2 2>&1 &
 CONSUMERPID=$!
 if test $WAIT != 0 ; then
@@ -446,6 +458,12 @@ sleep 3
 
 echo "Exporting config database for consumer from provider"
 $SLAPCAT -o ldif-wrap=no -F testrun/cfpro.d -b "cn=config,cn=consumer" -l testrun/config-consumer.ldif
+RC=$?
+if test $RC != 0 ; then
+	echo "slapcat failed ($RC)!"
+	exit $RC
+fi
+
 echo "Rewriting config database for loading on consumer"
 cp testrun/config-consumer.ldif testrun/consumer.ldif
 sed -i -e "s/^dn:\(.*\),cn=consumer/dn:\1/" testrun/consumer.ldif
@@ -453,6 +471,11 @@ mv $CFCON $CFCON.orig
 mkdir -p $CFCON
 echo "Reloading config database on consumer"
 $SLAPADD -F $CFCON -n 0 -l testrun/consumer.ldif
+RC=$?
+if test $RC != 0 ; then
+	echo "slapadd failed ($RC)!"
+	exit $RC
+fi
 
 echo "Restarting consumer slapd on TCP/IP port $PORT2..."
 $SLAPD -F $CFCON -h $URI2 -d $LVL >> $LOG2 2>&1 &
diff --git a/tests/scripts/lloadd/test003-cnconfig b/tests/scripts/lloadd/test003-cnconfig
--- a/tests/scripts/lloadd/test003-cnconfig
+++ b/tests/scripts/lloadd/test003-cnconfig
@@ -120,6 +120,12 @@ echo "Starting lloadd on TCP/IP port $PORT1..."
 . $CONFFILTER $BACKEND < $LLOADDUNREACHABLECONF > $CONF1.lloadd
 . $CONFFILTER $BACKEND < $SLAPDLLOADCONF > $CONF1.slapd
 $SLAPD -Tt -f $CONF1.slapd -F $CONF1.d -d $LVL > $LOG1 2>&1
+RC=$?
+if test $RC != 0 ; then
+    echo "slaptest failed ($RC)!"
+    exit $RC
+fi
+
 $SLAPD -F $CONF1.d -h $URI6 -d $LVL >> $LOG1 2>&1 &
 PID=$!
 if test $WAIT != 0 ; then
