ITS#10472 Check exit code of background jobs
Also improve KILLPIDS tracking.

Waiting on multiple jobs and relying on wait exit code being != 0 if at
least one process returned != 0 might not be portable but is the best we
can do for now. We can address that in the future.

diff --git a/tests/data/regressions/its9288/its9288 b/tests/data/regressions/its9288/its9288
--- a/tests/data/regressions/its9288/its9288
+++ b/tests/data/regressions/its9288/its9288
@@ -139,7 +139,8 @@ fi
 # Restart the remote server to invalidate TCP connection between proxy and remote
 echo "Killing and Re-starting remote slapd server on TCP/IP port $PORT1..."
 kill -HUP $SERVERPID
-wait $SERVERPID
+wait $SERVERPID || { kill -HUP $KILLPIDS; exit 1; }
+KILLPIDS=`echo "$KILLPIDS " | sed -e "s/ $SERVERPID / /"`
 
 $SLAPD -f $CONF1 -h "$URI1" -d $LVL >> $LOG1 2>&1 &
 SERVERPID=$!
@@ -177,10 +178,24 @@ if test $RC != 0 ; then
 	exit $RC
 fi
 
+wait $LDAPSEARCHPID
+RC=$?
+
+KILLPIDS=`echo "$KILLPIDS " | sed -e "s/ $LDAPSEARCHPID / /"`
+case $RC in
+0|52)
+	;;
+*)
+	echo "ldapmodify failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+	;;
+esac
+
 test $KILLSERVERS != no && kill -HUP $KILLPIDS 2>/dev/null
 
 echo ">>>>> Test succeeded"
 
-test $KILLSERVERS != no && wait
+test $KILLSERVERS != no && { wait $KILLPIDS || exit $?; }
 
 exit 0
