ITS#9599 Implement tiered load balancing

diff --git a/tests/scripts/lloadd/test003-cnconfig b/tests/scripts/lloadd/test003-cnconfig
--- a/tests/scripts/lloadd/test003-cnconfig
+++ b/tests/scripts/lloadd/test003-cnconfig
@@ -16,7 +16,7 @@
 echo "running defines.sh"
 . $SRCDIR/scripts/defines.sh
 
-mkdir -p $TESTDIR $DBDIR1 $DBDIR2
+mkdir -p $TESTDIR $CONF1.d $DBDIR1 $DBDIR2
 
 $SLAPPASSWD -g -n >$CONFIGPWF
 echo "rootpw `$SLAPPASSWD -T $CONFIGPWF`" >$TESTDIR/configpw.conf
@@ -157,10 +157,29 @@ fi
 
 echo "Deleting backends"
 
-for i in 1 2 3 4 ; do
-    echo "cn={0}server "$i",olcBackend={0}lload,cn=config"
+# weighted backends are sorted before we get to _cfadd to create their entries
+for i in 3 2 4 1 ; do
+    echo "cn={0}server $i,cn={1}tier 2,olcBackend={0}lload,cn=config"
     $LDAPDELETE -H $URI6 -D cn=config -y $CONFIGPWF \
-    "cn={0}server "$i",olcBackend={0}lload,cn=config" > /dev/null 2>&1
+    "cn={0}server $i,cn={1}tier 2,olcBackend={0}lload,cn=config" > /dev/null 2>&1
+    RC=$?
+    if test $RC != 0 ; then
+           echo "deleting server failed ($RC)!"
+           test $KILLSERVERS != no && kill -HUP $KILLPIDS
+           exit $RC
+    fi
+done
+
+echo "Testing cn=config searching..."
+$LDAPSEARCH -H $URI6 -D cn=config -y $CONFIGPWF \
+        -s sub -b "olcBackend={0}lload,cn=config" '(objectclass=*)' > /dev/null 2>&1
+
+echo "Deleting tiers"
+
+for i in 1 2; do
+    echo "cn={0}tier $i,olcBackend={0}lload,cn=config"
+    $LDAPDELETE -H $URI6 -D cn=config -y $CONFIGPWF \
+    "cn={0}tier $i,olcBackend={0}lload,cn=config" > /dev/null 2>&1
     RC=$?
     if test $RC != 0 ; then
            echo "deleting server failed ($RC)!"
@@ -185,9 +204,35 @@ if test $RC != 52 ; then
     exit $RC
 fi
 
-echo "Testing adding Server "
+echo "Testing adding a tier"
 $LDAPADD -D cn=config -H $URI6 -y $CONFIGPWF <<EOF > $TESTOUT 2>&1
-dn: cn=server 7,olcBackend={0}lload,cn=config
+dn: cn=roundrobin tier,olcBackend={0}lload,cn=config
+objectClass: olcBkLloadTierConfig
+olcBkLloadTierType: roundrobin
+EOF
+RC=$?
+if test $RC != 0 ; then
+    echo "ldapadd failed for cn=roundrobin tier ($RC)!"
+    test $KILLSERVERS != no && kill -HUP $KILLPIDS
+    exit $RC
+fi
+
+echo "Testing adding a weighted tier"
+$LDAPADD -D cn=config -H $URI6 -y $CONFIGPWF <<EOF > $TESTOUT 2>&1
+dn: cn=weighted tier,olcBackend={0}lload,cn=config
+objectClass: olcBkLloadTierConfig
+olcBkLloadTierType: weighted
+EOF
+RC=$?
+if test $RC != 0 ; then
+    echo "ldapadd failed for cn=weighted tier ($RC)!"
+    test $KILLSERVERS != no && kill -HUP $KILLPIDS
+    exit $RC
+fi
+
+echo "Testing adding a backend server"
+$LDAPADD -D cn=config -H $URI6 -y $CONFIGPWF <<EOF > $TESTOUT 2>&1
+dn: cn=server 7,cn={1}weighted tier,olcBackend={0}lload,cn=config
 objectClass: olcBkLloadBackendConfig
 cn: server 7
 olcBkLloadBackendUri: $URI3
@@ -196,6 +241,7 @@ olcBkLloadMaxPendingConns: 3
 olcBkLloadMaxPendingOps: 5
 olcBkLloadNumconns: 3
 olcBkLloadRetry: 5000
+olcBkLloadWeight: 10
 EOF
 RC=$?
 if test $RC != 0 ; then
@@ -276,7 +322,7 @@ $LDAPMODIFY -D cn=config -H $URI6 -y $CONFIGPWF <<EOF >> $TESTOUT 2>&1
 dn: olcBackend={0}lload,cn=config
 changetype: modify
 replace: olcBkLloadMaxPDUPerCycle
-olcBkLloadMaxPDUPerCycle: 2000
+olcBkLloadMaxPDUPerCycle: 0
 EOF
 
 RC=$?
@@ -374,7 +420,7 @@ fi
 echo "Testing backend attributes"
 echo "Testing olcBkLloadBindconns modify"
 $LDAPMODIFY -D cn=config -H $URI6 -y $CONFIGPWF <<EOF >> $TESTOUT 2>&1
-dn: cn={0}server 7,olcBackend={0}lload,cn=config
+dn: cn={0}server 7,cn={1}weighted tier,olcBackend={0}lload,cn=config
 changetype: modify
 replace: olcBkLloadBindconns
 olcBkLloadBindconns: 20
@@ -400,7 +446,7 @@ fi
 
 echo "Testing olcBkLloadMaxPendingConns modify"
 $LDAPMODIFY -D cn=config -H $URI6 -y $CONFIGPWF <<EOF >> $TESTOUT 2>&1
-dn: cn={0}server 7,olcBackend={0}lload,cn=config
+dn: cn={0}server 7,cn={1}weighted tier,olcBackend={0}lload,cn=config
 changetype: modify
 replace: olcBkLloadMaxPendingConns
 olcBkLloadMaxPendingConns: 30
diff --git a/tests/scripts/lloadd/test007-coherence b/tests/scripts/lloadd/test007-coherence
--- a/tests/scripts/lloadd/test007-coherence
+++ b/tests/scripts/lloadd/test007-coherence
@@ -28,8 +28,7 @@ if test $AC_lloadd = lloaddyes ; then
 fi
 
 # Monitor counts are unstable in the face of concurrency, since different
-# clients may get different upstreams assigned for their operations. This might
-# also change later when tiered load balancing is available.
+# clients may get different upstreams assigned for their operations.
 # Another constraint is that some global counts are updated by the statistics
 # collection task scheduled to run every second.
 #
@@ -203,9 +202,23 @@ if test $RC != 52 ; then
 	exit $RC
 fi
 
+echo "Adding first tier..."
+$LDAPMODIFY -D cn=config -H $URI6 -y $CONFIGPWF <<EOF >> $TESTOUT 2>&1
+dn: cn=first,olcBackend={0}lload,cn=config
+changetype: add
+objectClass: olcBkLloadTierConfig
+olcBkLloadTierType: roundrobin
+EOF
+RC=$?
+if test $RC != 0 ; then
+	echo "ldapadd failed for backend ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+fi
+
 echo "Adding first backend server..."
 $LDAPMODIFY -D cn=config -H $URI6 -y $CONFIGPWF <<EOF >> $TESTOUT 2>&1
-dn: cn=backend,olcBackend={0}lload,cn=config
+dn: cn=backend,cn={0}first,olcBackend={0}lload,cn=config
 changetype: add
 objectClass: olcBkLloadBackendConfig
 olcBkLloadBackendUri: $URI2
@@ -257,7 +270,7 @@ fi
 
 echo "Adding another backend server..."
 $LDAPMODIFY -D cn=config -H $URI6 -y $CONFIGPWF <<EOF >> $TESTOUT 2>&1
-dn: cn=server 2,olcBackend={0}lload,cn=config
+dn: cn=server 2,cn={0}first,olcBackend={0}lload,cn=config
 changetype: add
 objectClass: olcBkLloadBackendConfig
 olcBkLloadBackendUri: $URI3
