ITS#9929: more performance tweaks
For simple (non-nested) member compares, avoid unnecessary fetches
of dyngroups that can't match the filter.
cache filter/entry instance info across multiple dyn entries to
avoid refetching each filter entry for each dyngruop test.

diff --git a/tests/scripts/test044-dynlist b/tests/scripts/test044-dynlist
--- a/tests/scripts/test044-dynlist
+++ b/tests/scripts/test044-dynlist
@@ -763,7 +763,20 @@ echo "Testing filtered memberOf functionality..."
 echo "# Testing filtered memberOf functionality..." >> $SEARCHOUT
 $LDAPSEARCH -S "" -b "ou=People,$BASEDN" -H $URI1 \
 	-D "$BABSDN" -w bjensen \
-	'(&(memberOf=cn=Dynamic List of Members,ou=Dynamic Lists,dc=example,dc=com)(cn=Mark Elliot))' '*' 'memberOf' \
+	"(&(memberOf=cn=Dynamic List of Members,ou=Dynamic Lists,$BASEDN)(cn=Mark Elliot))" '*' 'memberOf' \
+	>> $SEARCHOUT 2>&1
+RC=$?
+if test $RC != 0 ; then
+	echo "ldapsearch failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+fi
+
+echo "Testing filtered member functionality..."
+echo "# Testing filtered member functionality..." >> $SEARCHOUT
+$LDAPSEARCH -S "" -b "$BASEDN" -H $URI1 \
+	-D "$BABSDN" -w bjensen \
+	"(member=cn=Jane Doe,ou=Alumni Association,ou=People,$BASEDN)" \
 	>> $SEARCHOUT 2>&1
 RC=$?
 if test $RC != 0 ; then
