ITS#10250 tests: Do not silently succeed anymore

diff --git a/tests/scripts/test045-syncreplication-proxied b/tests/scripts/test045-syncreplication-proxied
--- a/tests/scripts/test045-syncreplication-proxied
+++ b/tests/scripts/test045-syncreplication-proxied
@@ -712,53 +712,9 @@ echo "$CHECK < Comparing retrieved entries from provider and consumer..."
 $CMP $PROVIDERFLT $CONSUMERFLT > $CMPOUT
 
 if test $? != 0 ; then
-	# FIXME: keep the original workaround in place, in case we needed again
-	if test 1 = 1 ; then
-		echo "test failed - provider and consumer databases differ"
-		test $KILLSERVERS != no && kill -HUP $KILLPIDS
-		exit 1
-	fi
-
-	echo "	test failed - provider and consumer databases differ (ignored by now)"
-	echo "	Stopping proxy to see if it auto-recovers..."
-	kill -HUP $PROXYPID
-	wait $PROXYPID
-
-	echo "	${CHECK}.1 > Restarting proxy..."
-	echo "======================= RESTART =======================" >> $LOG3
-	$SLAPD -f $CONF3 -h $URI3 -d $LVL >> $LOG3 2>&1 &
-	PROXYPID=$!
-	if test $WAIT != 0 ; then
-		echo PROXYPID $PROXYPID
-		read foo
-	fi
-	KILLPIDS="$PROVIDERPID $CONSUMERPID $PROXYPID"
-
-	echo "	Waiting $SLEEP2 seconds for syncrepl to receive changes..."
-	sleep $SLEEP2
-
-	#echo "Using ldapsearch to read all the entries from the consumer..."
-	$LDAPSEARCH -S "" -b "$BASEDN" -H $URI2 \
-		'(objectClass=*)' > "${CONSUMEROUT}.5.1" 2>&1
-	RC=$?
-
-	if test $RC != 0 ; then
-		echo "	ldapsearch failed at consumer ($RC)!"
-		test $KILLSERVERS != no && kill -HUP $KILLPIDS
-		exit $RC
-	fi
-
-	#echo "Filtering consumer results..."
-	$LDIFFILTER < "${CONSUMEROUT}.5.1" > $CONSUMERFLT
-
-	echo "	${CHECK}.1 < Comparing retrieved entries from provider and consumer..."
-	$CMP $PROVIDERFLT $CONSUMERFLT > $CMPOUT
-
-	if test $? != 0 ; then
-		echo "	test failed - provider and consumer databases differ"
-		test $KILLSERVERS != no && kill -HUP $KILLPIDS
-		exit 1
-	fi
+	echo "test failed - provider and consumer databases differ"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit 1
 fi
 
 #
@@ -852,10 +808,9 @@ echo "$CHECK < Comparing retrieved entries from provider and consumer..."
 $CMP $PROVIDERFLT $CONSUMERFLT > $CMPOUT
 
 if test $? != 0 ; then
-	echo "test failed - provider and consumer databases differ (ignored by now)"
-	#echo "test failed - provider and consumer databases differ"
-	#test $KILLSERVERS != no && kill -HUP $KILLPIDS
-	#exit 1
+	echo "test failed - provider and consumer databases differ"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit 1
 fi
 
 test $KILLSERVERS != no && kill -HUP $KILLPIDS
