ITS#6198 Introduce restrictop functionality

diff --git a/tests/scripts/test006-acls b/tests/scripts/test006-acls
--- a/tests/scripts/test006-acls
+++ b/tests/scripts/test006-acls
@@ -63,6 +63,120 @@ fi
 
 cat /dev/null > $SEARCHOUT
 
+echo "Testing restrictop handling..."
+
+echo "# A search by rootdn gets waved through"
+$LDAPSEARCH -H $URI1 -D "$MANAGERDN" -w $PASSWD \
+	-b "$BABSDN" -s base \
+	-e "assert=(entryDN=)" "(objectclass=*)" \
+	>>$SEARCHOUT 2>&1
+RC=$?
+case $RC in
+122)
+	;;
+0)
+	echo "ldapsearch should have failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit 1
+	;;
+*)
+	echo "ldapsearch failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+	;;
+esac
+
+echo "# A search with a control that gets dropped"
+$LDAPSEARCH -H $URI1 -b "$BABSDN" -s base -M \
+	"(objectclass=*)" >>$SEARCHOUT 2>&1
+RC=$?
+if test $RC != 0 ; then
+	echo "ldapsearch failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+fi
+
+echo "# A search with a control that can't be dropped"
+$LDAPSEARCH -H $URI1 -b "$BABSDN" -s base -MM \
+	"(objectclass=*)" >>$SEARCHOUT 2>&1
+RC=$?
+case $RC in
+53)
+	;;
+0)
+	echo "ldapsearch should have failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit 1
+	;;
+*)
+	echo "ldapsearch failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+	;;
+esac
+
+echo "# Same search by a user that's allowed to use it"
+$LDAPSEARCH -H $URI1 -D "$BJORNSDN" -w bjorn -b "$BABSDN" -s base -MM \
+	"(objectclass=*)" >>$SEARCHOUT 2>&1
+RC=$?
+if test $RC != 0 ; then
+	echo "ldapsearch failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+fi
+
+echo "# A search with a control combination that is stripped"
+$LDAPSEARCH -H $URI1 -b "$BABSDN" -s base -M -e "assert=(entryDN=)" \
+	"(objectclass=*)" >>$SEARCHOUT 2>&1
+RC=$?
+if test $RC != 0 ; then
+	echo "ldapsearch failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+fi
+
+echo "# A search with a control combination that is rejected"
+$LDAPSEARCH -H $URI1 -D "$BABSDN" -w bjensen \
+	-b "$BABSDN" -s base -M -e "assert=(entryDN=)" \
+	"(objectclass=*)" >>$SEARCHOUT 2>&1
+RC=$?
+case $RC in
+53)
+	;;
+0)
+	echo "ldapsearch should have failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit 1
+	;;
+*)
+	echo "ldapsearch failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+	;;
+esac
+
+echo "# A password modify is not allowed"
+$LDAPPASSWD -H $URI1 -D "$BABSDN" -w bjensen -a bjensen -s changed \
+	>> $SEARCHOUT 2>&1
+RC=$?
+case $RC in
+1|53)
+	# ldappasswd currently returns 1 on any error
+	;;
+0)
+	echo "ldappasswd should have failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit 1
+	;;
+*)
+	echo "ldappasswd failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+	;;
+esac
+
+cat /dev/null > $SEARCHOUT
+
 echo "# Try to read an entry inside the Alumni Association container.
 # It should give us noSuchObject if we're not bound..." \
 >> $SEARCHOUT
