Check slapadd result before continuing with test

diff --git a/tests/scripts/test058-syncrepl-asymmetric b/tests/scripts/test058-syncrepl-asymmetric
--- a/tests/scripts/test058-syncrepl-asymmetric
+++ b/tests/scripts/test058-syncrepl-asymmetric
@@ -175,6 +175,12 @@ olcDatabase: {0}config
 olcRootPW:< file://$CONFIGPWF
 
 EOF
+	RC=$?
+	if test $RC != 0 ; then
+		echo "slapadd failed ($RC)!"
+		exit $RC
+	fi
+
 	ID=`expr $ID + 1`
 done
 
@@ -191,6 +197,12 @@ olcDatabase: {0}config
 olcRootPW:< file://$CONFIGPWF
 
 EOF
+
+RC=$?
+if test $RC != 0 ; then
+	echo "slapadd failed ($RC)!"
+	exit $RC
+fi
 done
 
 echo "Starting central provider slapd on TCP/IP port $PORT1..."
diff --git a/tests/scripts/test063-delta-multiprovider b/tests/scripts/test063-delta-multiprovider
--- a/tests/scripts/test063-delta-multiprovider
+++ b/tests/scripts/test063-delta-multiprovider
@@ -214,6 +214,12 @@ olcDatabase: {3}monitor
 EOF
 
 $SLAPADD -F $CFDIR -n 0  -d-1< $TMP > $TESTOUT 2>&1
+RC=$?
+if test $RC != 0 ; then
+	echo "slapadd failed ($RC)!"
+	exit $RC
+fi
+
 PORT=`eval echo '$PORT'$n`
 echo "Starting server $n on TCP/IP port $PORT..."
 cd ${XDIR}${n}
diff --git a/tests/scripts/test076-authid-rewrite b/tests/scripts/test076-authid-rewrite
--- a/tests/scripts/test076-authid-rewrite
+++ b/tests/scripts/test076-authid-rewrite
@@ -31,6 +31,12 @@ $SLAPPASSWD -g -n >$CONFIGPWF
 echo "Starting slapd on TCP/IP port $PORT1... $PWD"
 . $CONFFILTER $BACKEND < $DYNAMICCONF > $CONFLDIF
 $SLAPADD -F $CONFDIR -n 0 -l $CONFLDIF
+RC=$?
+if test $RC != 0 ; then
+	echo "slapadd failed ($RC)!"
+	exit $RC
+fi
+
 cd $TESTDIR
 $SLAPD -F ./slapd.d -h $URI1 -d $LVL > $LOG1 2>&1 &
 PID=$!
diff --git a/tests/scripts/test083-argon2 b/tests/scripts/test083-argon2
--- a/tests/scripts/test083-argon2
+++ b/tests/scripts/test083-argon2
@@ -97,6 +97,11 @@ EOF
 fi
 
 $SLAPADD -F $CONFDIR -n 0 -l $TESTDIR/config.ldif
+RC=$?
+if test $RC != 0 ; then
+	echo "slapadd failed ($RC)!"
+	exit $RC
+fi
 
 echo "Starting slapd on TCP/IP port $PORT1..."
 $SLAPD -F $CONFDIR -h $URI1 -d $LVL > $LOG1 2>&1 &
