Need to use -s base with "cn=monitor". Replace simple sleep in test008 with search loop

diff --git a/tests/scripts/test008-concurrency b/tests/scripts/test008-concurrency
--- a/tests/scripts/test008-concurrency
+++ b/tests/scripts/test008-concurrency
@@ -10,11 +10,14 @@ if test $# -eq 1 ; then
 fi
 
 echo "running defines.sh $SRCDIR $BACKEND"
+
 . $SRCDIR/scripts/defines.sh
+
+echo "Datadir is $DATADIR"
 
 echo "Cleaning up in $DBDIR..."
 
-rm -f $DBDIR/[!C]*
+rm -f $DBDIR/[!C*
 
 echo "Running ldif2ldbm to build slapd database..."
 $LDIF2LDBM -f $CONF -i $LDIF -e ../servers/slapd/tools
@@ -24,11 +27,14 @@ if test $RC != 0 ; then
 	exit $RC
 fi
 
+echo "Waiting 5 seconds for ldif2ldbm to build slapd database..."
+sleep 5
+
 echo "Starting slapd on TCP/IP port $PORT..."
 $SLAPD -f $CONF -p $PORT -d $LVL $TIMING > $MASTERLOG 2>&1 &
 PID=$!
 
-echo "Testing slapd searching..."
+echo "Using ldapsearch to check that slapd is running..."
 for i in 0 1 2 3 4 5; do
 	$LDAPSEARCH -L -s base -b "$MONITOR" -h localhost -p $PORT \
 		'objectclass=*' > /dev/null 2>&1
@@ -39,54 +45,26 @@ for i in 0 1 2 3 4 5; do
 	fi
 done
 
+echo "Using tester for concurrent server access..."
+$SLAPDTESTER -b "$BASEDN" -P "$PROGDIR" -d "$DATADIR" -h localhost -p $PORT -D "$MANAGERDN" -w $PASSWD -l 50
+RC=$?
+
 if test $RC != 0 ; then
-	echo "ldapsearch failed!"
-	kill -HUP $PID
+	echo "slapd-tester failed!"
 	exit $RC
-fi
+fi 
 
-cat /dev/null > $SEARCHOUT
-
-echo "Testing exact searching..."
+echo "Using ldapsearch to retrieve all the entries..."
 $LDAPSEARCH -L -S "" -b "$BASEDN" -h localhost -p $PORT \
-	'sn=jensen' >> $SEARCHOUT 2>&1
-if test $RC != 0 ; then
-	echo "ldapsearch failed!"
-	kill -HUP $PID
-	exit $RC
-fi
-
-echo "Testing OR searching..."
-$LDAPSEARCH -L -S "" -b "$BASEDN" -h localhost -p $PORT \
-	'(|(objectclass=rfc822mailgroup)(sn=jones))' >> $SEARCHOUT 2>&1
-if test $RC != 0 ; then
-	echo "ldapsearch failed!"
-	kill -HUP $PID
-	exit $RC
-fi
-
-echo "Testing AND matching and ends-with searching..."
-$LDAPSEARCH -L -S "" -b "$BASEDN" -h localhost -p $PORT \
-	'(&(objectclass=rfc822mailgroup)(cn=A*))' >> $SEARCHOUT 2>&1
-if test $RC != 0 ; then
-	echo "ldapsearch failed!"
-	kill -HUP $PID
-	exit $RC
-fi
-
-echo "Testing NOT searching..."
-$LDAPSEARCH -L -S "" -b "$BASEDN" -h localhost -p $PORT \
-	'(!(objectclass=person))' >> $SEARCHOUT 2>&1
-if test $RC != 0 ; then
-	echo "ldapsearch failed!"
-	kill -HUP $PID
-	exit $RC
-fi
+			'objectClass=*' > $SEARCHOUT 2>&1
+RC=$?
 
 kill -HUP $PID
 
-TESTOUT=$SEARCHOUT
-LDIF=$SEARCHOUTMASTER
+if test $RC != 0 ; then
+	echo "ldapsearch failed!"
+	exit $RC
+fi
 
 echo "Filtering ldapsearch results..."
 . $SRCDIR/scripts/acfilter.sh < $SEARCHOUT > $SEARCHFLT
@@ -96,7 +74,7 @@ echo "Comparing filter output..."
 cmp $SEARCHFLT $LDIFFLT
 
 if test $? != 0 ; then
-	echo "Comparison failed"
+	echo "comparison failed - database was not created correctly"
 	exit 1
 fi
 
